### ISSUE TITLE
Cant Read Hidden Folder File

### ISSUE THREAD

**Issue by dhameliyamilan** [NewtronLabs/EasyFolderPicker#1]
This Plugin cant read hidden folder files.
Actually, I want All Whatsapp status files And location Is **/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media/.Statuses** But this path Always Reurn [] Empty File List

**Comment by NewtronLabs** [comment]
Hi @dhameliyamilan,

Could you provide us with more information. For example, what version of Android are you testing this on? 

Thanks,
Amy
